### ISSUE TITLE
What branch is the release based on?

### ISSUE THREAD

**Issue by colemanw** [TechToThePeople/group2summary#3]
Hey Xavier, I wanted to try this extension and see if it was compatible with https://github.com/civicrm/org.civicrm.contactlayout or if it needed a patch, but I'm confused by all the branches. The latest release of this extension is based on commit 3be54ce31685f0f2e338e7c1c63dd63cf09d3dd5, yet that commit doesn't belong to any branch! Branch "Ajax" is set up as the default branch when you clone this repo, yet it hasn't been updated in 5 years.
So, which branch is the release based on? And which branch should I check out to test compatibility?
Thanks.

**Comment by tttp** [comment]
ouch, good question. I'm away from keyboard till next week, I'll check on monday

**Comment by colemanw** [comment]
The master branch seems to be most up-to-date, so I pushed a small PR to ensure compatibility to that branch. See #4

**Comment by TomCrawshaw** [comment]
These are both great extensions (Thanks!), and not wanting to choose between them, I tried deleting this check in group2summary.tpl:

  if ($(".crm-contact_type_label").length == 0) {
    CRM.alert("Someone has changed the summary layout, groups can't be displayed properly");
    return;
  }

and found it worked... Groups reinstated to the new Contact summary screen created with contactlayout. Is this check required?

**Comment by colemanw** [comment]
@TomCrawshaw that's basically what I did in #4. @tttp can you please check that PR?

**Comment by tttp** [comment]
So if it works without, I'd go for "no, not needed"

and that was written a gazillion years ago, whatever purpose it had, probably got lost ;)

**Comment by tttp** [comment]
PR merged

I will try to find the time to do the create new version change it here and there and hope it will go through the extension, but I gave up last time

@colemanw is this easier now to publish a new version or do we still have to deal with modifying an xml file and git tag and voodoo dance?

**Comment by TomCrawshaw** [comment]
@colemanw yes, I can see now that the PR does seem to do the same; I had thought it would still fail, albeit without the alert.

**Comment by mlutfy** [comment]
Moving issues to Gitlab: https://lab.civicrm.org/extensions/group2summary/-/issues/3
