### ISSUE TITLE
Incompatible with PHP 8.1

### ISSUE THREAD

**Issue by ghost** [TechToThePeople/group2summary#8]
It seems that this lovely extension is not compatible with PHP 8.1.

Tried on WordPress 6.1.1 with CiviCRM 5.55.2 on PHP 8.1.13.

**Comment by tttp** [comment]
Hi,

Would you have the time to update it? contributions more than welcome, but as I don't have a lot of users on civi these days, I'm afraid I'm not going to have the time to look at it

**Comment by mlutfy** [comment]
PHP 8 compatibility was fixed by #7, it's only missing a release tag.

@tttp Since this is a "reviewed extension" available in-app in CiviCRM, I can help with quickfixes and/or move it to Gitlab (or I can remove the reviewed flag, if you prefer).

**Comment by ghost** [comment]
Thank you very much @mlutfy ! I'm not into PHP because I only implement things.

**Comment by mlutfy** [comment]
@eptbertram Can you re-open the issue? The extension is still missing a release tag (to create an official release, so that it does not crash CiviCRM if people install the extension from the in-app extension browser).

**Comment by ghost** [comment]
sorry

**Comment by mlutfy** [comment]
Moving issues to Gitlab: https://lab.civicrm.org/extensions/group2summary/-/issues/8
